### ISSUE TITLE
some error for these project!

### ISSUE THREAD

**Issue by HuangLian126** [Tung-I/Dual-awareness-Attention-for-Few-shot-Object-Detection#1]
Thanks for your nice work. I find some errors:

1) Traceback (most recent call last):
  File "train.py", line 79, in <module>
    pre_weight = False if args.finetune or args.resume else True
AttributeError: 'Namespace' object has no attribute 'finetune'

2)  File "utils.py", line 21, in <module>
    from model.framework.cisa import CISARCNN
ModuleNotFoundError: No module named 'model.framework.cisa'

Besides, can you explain the meanings of  OracleLoader, FinetuneLoader and FewShotLoader?

**Comment by Tung-I** [comment]
Thanks for raising the issues. I attempt to reorganize the source code and it remains semi-finished here with some obvious errors. Unfortunately, I am too busy to tackle this project currently, and I will finish it before long. The OracleLoader, FinetuneLoader and FewShotLoader denote different data loaders used in my experiments.

**Comment by michaelku1** [comment]
> 

RTDP (read the damn paper)

**Comment by Fly-dream12** [comment]
Have you visualized the attention in this project？ @HuangLian126 @Tung-I
