### ISSUE TITLE
How to train more GPUs

### ISSUE THREAD

**Issue by luoyq6** [Tung-I/Dual-awareness-Attention-for-Few-shot-Object-Detection#34]
Traceback (most recent call last):
  File "train1.py", line 240, in <module>
    rois_label, correlation_feat2, rois_label2 = model(im_data, im_info, gt_boxes, num_boxes, support_ims)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 180, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 56, in forward
    assert all(i.device.type != 'cpu' for i in inputs), (
AssertionError: Gather function not implemented for CPU tensors

**Comment by giangdip2410** [comment]
I faced the same issue for training mutil GPUs. @Tung-I : please give us your advice, thank you.
